set_property PACKAGE_PIN G17 [get_ports UART_0_rxd]
set_property PACKAGE_PIN H20 [get_ports UART_0_txd]

set_property IOSTANDARD LVTTL [get_ports UART_0_rxd]
set_property IOSTANDARD LVTTL [get_ports UART_0_txd]

set_property PACKAGE_PIN T15 [get_ports ext_io0_0]
set_property PACKAGE_PIN R14 [get_ports ext_io1_0]
set_property PACKAGE_PIN P14 [get_ports ext_sck_0]
set_property PACKAGE_PIN T14 [get_ports ext_ss_0]
set_property PACKAGE_PIN F16 [get_ports {GPIO_0_tri_o[3]}]
set_property PACKAGE_PIN L19 [get_ports {GPIO_0_tri_o[2]}]
set_property PACKAGE_PIN M19 [get_ports {GPIO_0_tri_o[1]}]
set_property PACKAGE_PIN M17 [get_ports {GPIO_0_tri_o[0]}]
set_property IOSTANDARD LVTTL [get_ports {GPIO_0_tri_o[3]}]
set_property IOSTANDARD LVTTL [get_ports {GPIO_0_tri_o[2]}]
set_property IOSTANDARD LVTTL [get_ports {GPIO_0_tri_o[1]}]
set_property IOSTANDARD LVTTL [get_ports {GPIO_0_tri_o[0]}]
set_property IOSTANDARD LVTTL [get_ports ext_io0_0]
set_property IOSTANDARD LVTTL [get_ports ext_io1_0]
set_property IOSTANDARD LVTTL [get_ports ext_sck_0]
set_property IOSTANDARD LVTTL [get_ports ext_ss_0]

set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
